import type {
  FintechColorToken,
  FintechComponentSpec,
  FintechElevationToken,
  FintechPatternSpec,
  FintechSpacingToken,
  FintechTypeStyle,
} from "./types"

export const fintechColorTokens: FintechColorToken[] = [
  {
    name: "Ember Trust",
    token: "--fin-brand",
    value: "#ea580c",
    darkValue: "#f97316",
    role: "Primary brand actions, active navigation, trusted decision points",
    contrast: "4.8:1 on light surfaces, 5.9:1 on dark surfaces",
    tone: "brand",
  },
  {
    name: "Warm Intelligence",
    token: "--fin-accent",
    value: "#f97316",
    darkValue: "#fb923c",
    role: "Insights, smart recommendations, verified financial health",
    contrast: "4.5:1 on light surfaces for large text, accent-only in dark",
    tone: "info",
  },
  {
    name: "Ink",
    token: "--fin-text-primary",
    value: "#101828",
    darkValue: "#f4f7fb",
    role: "Primary text, balances, table values, critical confirmations",
    contrast: "16.3:1 light, 13.8:1 dark",
    tone: "neutral",
  },
  {
    name: "Slate",
    token: "--fin-text-secondary",
    value: "#475467",
    darkValue: "#b8c2d6",
    role: "Secondary labels, explanations, timestamps, metadata",
    contrast: "7.4:1 light, 8.6:1 dark",
    tone: "neutral",
  },
  {
    name: "Canvas",
    token: "--fin-bg",
    value: "#f6f8fb",
    darkValue: "#08111f",
    role: "Application background and page bands",
    contrast: "Pair with text-primary only",
    tone: "neutral",
  },
  {
    name: "Surface",
    token: "--fin-surface",
    value: "#ffffff",
    darkValue: "#101a2b",
    role: "Cards, tables, panels, form sections",
    contrast: "Pair with text-primary or text-secondary",
    tone: "neutral",
  },
  {
    name: "Surface Raised",
    token: "--fin-surface-raised",
    value: "#fbfcfe",
    darkValue: "#16243a",
    role: "Dropdowns, drawers, elevated confirmation surfaces",
    contrast: "Pair with text-primary or text-secondary",
    tone: "neutral",
  },
  {
    name: "Border",
    token: "--fin-border",
    value: "#d8dee8",
    darkValue: "#26364f",
    role: "Separators, table rows, controls, card outlines",
    contrast: "Non-text only",
    tone: "neutral",
  },
  {
    name: "Success",
    token: "--fin-success",
    value: "#07875b",
    darkValue: "#59d79d",
    role: "Completed transfers, verified accounts, resolved checks",
    contrast: "4.8:1 light, 8.2:1 dark",
    tone: "success",
  },
  {
    name: "Warning",
    token: "--fin-warning",
    value: "#b54708",
    darkValue: "#f7b955",
    role: "Pending review, limit approaching, non-blocking caution",
    contrast: "5.3:1 light, 9.9:1 dark",
    tone: "warning",
  },
  {
    name: "Error",
    token: "--fin-error",
    value: "#b42318",
    darkValue: "#ff9b8f",
    role: "Failed payments, invalid input, destructive actions",
    contrast: "6.7:1 light, 8.3:1 dark",
    tone: "error",
  },
  {
    name: "Pending",
    token: "--fin-pending",
    value: "#6941c6",
    darkValue: "#c4b5fd",
    role: "Processing transactions, awaiting approval, queued tasks",
    contrast: "6.1:1 light, 8.6:1 dark",
    tone: "pending",
  },
  {
    name: "Income",
    token: "--fin-income",
    value: "#047857",
    darkValue: "#6ee7b7",
    role: "Incoming transfers, deposits, positive cash movement",
    contrast: "5.5:1 light, 10.1:1 dark",
    tone: "income",
  },
  {
    name: "Expense",
    token: "--fin-expense",
    value: "#c2410c",
    darkValue: "#fdba74",
    role: "Outgoing spend, card payments, withdrawals",
    contrast: "4.9:1 light, 8.4:1 dark",
    tone: "expense",
  },
  {
    name: "Profit",
    token: "--fin-profit",
    value: "#15803d",
    darkValue: "#86efac",
    role: "Growth, portfolio gain, margin expansion",
    contrast: "4.7:1 light, 9.8:1 dark",
    tone: "profit",
  },
  {
    name: "Loss",
    token: "--fin-loss",
    value: "#be123c",
    darkValue: "#fda4af",
    role: "Portfolio decline, negative variance, overdue exposure",
    contrast: "5.8:1 light, 8.7:1 dark",
    tone: "loss",
  },
  {
    name: "Risk",
    token: "--fin-risk",
    value: "#9a3412",
    darkValue: "#fed7aa",
    role: "Fraud flags, suspicious account activity, high consequence actions",
    contrast: "6.4:1 light, 10.3:1 dark",
    tone: "risk",
  },
  {
    name: "Safe",
    token: "--fin-safe",
    value: "#065f46",
    darkValue: "#99f6e4",
    role: "Trusted device, insured funds, secure connection",
    contrast: "7.1:1 light, 11.4:1 dark",
    tone: "safe",
  },
]

export const fintechTypeStyles: FintechTypeStyle[] = [
  {
    name: "Display",
    token: "type.display",
    size: "44px",
    lineHeight: "52px",
    weight: "700",
    usage: "Product-level moments and catalog section leads",
    sample: "Operating balance",
  },
  {
    name: "Page title",
    token: "type.page",
    size: "32px",
    lineHeight: "40px",
    weight: "650",
    usage: "Dashboard, analytics, and account pages",
    sample: "Treasury dashboard",
  },
  {
    name: "Section title",
    token: "type.section",
    size: "22px",
    lineHeight: "30px",
    weight: "650",
    usage: "Major grouped content areas",
    sample: "Cash movement",
  },
  {
    name: "Card title",
    token: "type.card",
    size: "16px",
    lineHeight: "24px",
    weight: "620",
    usage: "Cards, panels, modals, popovers",
    sample: "Available credit",
  },
  {
    name: "Body",
    token: "type.body",
    size: "14px",
    lineHeight: "22px",
    weight: "400",
    usage: "Primary reading text and descriptions",
    sample: "Settlement completes by 5:00 PM today.",
  },
  {
    name: "Caption",
    token: "type.caption",
    size: "12px",
    lineHeight: "18px",
    weight: "450",
    usage: "Timestamps, helper text, secondary metadata",
    sample: "Updated 2 minutes ago",
  },
  {
    name: "Label",
    token: "type.label",
    size: "11px",
    lineHeight: "16px",
    weight: "700",
    usage: "Field labels, badges, filter labels",
    sample: "AVAILABLE CASH",
  },
  {
    name: "Data numeric",
    token: "type.numeric",
    size: "28px",
    lineHeight: "34px",
    weight: "720",
    usage: "Balances, KPIs, transfer amounts",
    sample: "$482,490.24",
    numeric: true,
  },
  {
    name: "Table",
    token: "type.table",
    size: "13px",
    lineHeight: "20px",
    weight: "500",
    usage: "Dense rows, transaction lists, admin workflows",
    sample: "ACH credit - Stripe payout",
  },
  {
    name: "Button",
    token: "type.button",
    size: "13px",
    lineHeight: "18px",
    weight: "650",
    usage: "Primary, secondary, destructive, and ghost actions",
    sample: "Send money",
  },
]

export const fintechSpacingTokens: FintechSpacingToken[] = [
  { name: "2xs", token: "space.2", value: "2px", usage: "Hairline offsets and compact icon alignment" },
  { name: "xs", token: "space.4", value: "4px", usage: "Dense table cells and badge internals" },
  { name: "sm", token: "space.8", value: "8px", usage: "Control gaps, compact rows, chip spacing" },
  { name: "md", token: "space.12", value: "12px", usage: "Form groups, list rows, action clusters" },
  { name: "lg", token: "space.16", value: "16px", usage: "Card padding, dashboard gutters, mobile panels" },
  { name: "xl", token: "space.24", value: "24px", usage: "Section rhythm, modal padding, grouped analytics" },
  { name: "2xl", token: "space.32", value: "32px", usage: "Page blocks and responsive grid spacing" },
  { name: "3xl", token: "space.48", value: "48px", usage: "Major page bands and onboarding screens" },
  { name: "4xl", token: "space.64", value: "64px", usage: "Catalog chapters and large empty states" },
]

export const fintechElevationTokens: FintechElevationToken[] = [
  {
    name: "Flat",
    token: "elevation.0",
    value: "0 0 0 1px var(--fin-border)",
    usage: "Default cards, tables, navigation, dense admin surfaces",
  },
  {
    name: "Raised",
    token: "elevation.1",
    value: "0 8px 24px rgba(15, 23, 42, 0.08)",
    usage: "Hover surfaces, active panels, floating KPI details",
  },
  {
    name: "Overlay",
    token: "elevation.2",
    value: "0 18px 48px rgba(15, 23, 42, 0.16)",
    usage: "Dropdowns, popovers, bottom sheets, drawers",
  },
  {
    name: "Critical",
    token: "elevation.risk",
    value: "0 0 0 1px rgba(180, 35, 24, 0.24), 0 16px 40px rgba(180, 35, 24, 0.12)",
    usage: "Risk warnings, destructive confirmations, fraud review",
  },
]

export const fintechComponentSpecs: FintechComponentSpec[] = [
  {
    name: "Sidebar",
    category: "Navigation",
    description: "Persistent product navigation with account switcher, status counts, and collapsible groups.",
    states: ["default", "hover", "focus"],
    props: ["items", "value", "actions", "children"],
    accessibility: "Use landmarks, current-page state, and text labels even when collapsed.",
  },
  {
    name: "Top navigation",
    category: "Navigation",
    description: "Global account context, search, notifications, profile, and secure-session status.",
    states: ["default", "focus"],
    props: ["items", "actions", "children"],
    accessibility: "Search and menus keep keyboard focus visible and announce unread counts.",
  },
  {
    name: "Mobile bottom navigation",
    category: "Navigation",
    description: "Thumb-reachable primary destinations for wallet, payments, cards, insights, and profile.",
    states: ["default", "hover", "focus"],
    props: ["items", "value"],
    accessibility: "Minimum 44px targets and explicit active route labels.",
  },
  {
    name: "Breadcrumbs",
    category: "Navigation",
    description: "Hierarchy for account, transaction, statement, and settings detail pages.",
    states: ["default", "hover", "focus"],
    props: ["items"],
    accessibility: "Use ordered navigation and avoid truncating the current page label.",
  },
  {
    name: "Tabs",
    category: "Navigation",
    description: "Switches between product contexts like accounts, payments, analytics, disputes, and settings.",
    states: ["default", "hover", "focus", "disabled"],
    props: ["items", "value", "size"],
    accessibility: "Use roving focus and keep tab labels persistent.",
  },
  {
    name: "Buttons",
    category: "Buttons",
    description: "Primary, secondary, ghost, destructive, icon, loading, and disabled command states.",
    states: ["default", "hover", "focus", "loading", "disabled"],
    props: ["variant", "size", "state", "tone", "children"],
    accessibility: "Never communicate destructive intent through color alone.",
  },
  {
    name: "Inputs",
    category: "Inputs",
    description: "Text, amount, search, select, multi-select, date, OTP, password, card number, and currency controls.",
    states: ["default", "focus", "disabled", "success", "error"],
    props: ["label", "value", "description", "state", "tone"],
    accessibility: "Associate helper and error text with the control; use tabular numerals for money.",
  },
  {
    name: "Cards",
    category: "Cards",
    description: "Balance, account, card preview, insight, transaction summary, analytics, alert, and product cards.",
    states: ["default", "hover", "focus", "loading"],
    props: ["label", "value", "description", "status", "tone", "actions", "children"],
    accessibility: "Interactive cards use a single focus target and visible title.",
  },
  {
    name: "Data components",
    category: "Data",
    description: "Tables, transactions, statements, filters, sorting, pagination, charts, KPIs, trends, and comparisons.",
    states: ["default", "hover", "focus", "loading"],
    props: ["items", "value", "status", "tone", "children"],
    accessibility: "Use row headers, captions where needed, and text equivalents for chart trends.",
  },
  {
    name: "Feedback components",
    category: "Feedback",
    description: "Toasts, alerts, inline validation, empty states, loading states, skeletons, confirmations, and recovery.",
    states: ["default", "loading", "success", "error"],
    props: ["tone", "status", "label", "description", "actions"],
    accessibility: "Use appropriate live regions for async feedback and preserve user-entered data on errors.",
  },
  {
    name: "Security components",
    category: "Security",
    description: "Authentication, OTP, trusted devices, risk warnings, consent, secure payment, and timeout warnings.",
    states: ["default", "focus", "loading", "success", "error"],
    props: ["status", "tone", "label", "description", "actions"],
    accessibility: "Critical flows require explicit confirmation text and non-color risk labels.",
  },
  {
    name: "Overlays",
    category: "Overlays",
    description: "Modal, bottom sheet, drawer, popover, tooltip, and confirmation dialog patterns.",
    states: ["default", "focus", "loading", "disabled"],
    props: ["size", "state", "tone", "children", "actions"],
    accessibility: "Trap focus in blocking overlays and restore focus to the trigger.",
  },
]

export const fintechPatternSpecs: FintechPatternSpec[] = [
  {
    name: "Add money",
    trigger: "User chooses a funding method from wallet or account balance.",
    requiredData: ["Funding source", "Destination account", "Amount", "Availability timing"],
    primaryStates: ["Source selection", "Amount entry", "Review", "Processing", "Complete"],
    riskBehavior: "Surface limits, settlement timing, fees, and reversible/irreversible status before confirmation.",
    previewKind: "money",
  },
  {
    name: "Send money",
    trigger: "User initiates payment to a saved recipient, bank account, or wallet handle.",
    requiredData: ["Recipient", "Amount", "Funding source", "Memo", "Delivery rail"],
    primaryStates: ["Recipient", "Amount", "Review", "Risk gate", "Receipt"],
    riskBehavior: "High-value or new-recipient sends require step-up verification and consequence copy.",
    previewKind: "transfer",
  },
  {
    name: "Request money",
    trigger: "User creates a payable request or invoice link.",
    requiredData: ["Payer", "Amount", "Due date", "Reason", "Reminder cadence"],
    primaryStates: ["Draft", "Sent", "Viewed", "Paid", "Expired"],
    riskBehavior: "Warn about expired links and unverified payer identities.",
    previewKind: "request",
  },
  {
    name: "Card payment",
    trigger: "User authorizes a card transaction or configures a virtual card.",
    requiredData: ["Card", "Merchant", "Amount", "Limit", "Authentication"],
    primaryStates: ["Card selection", "Authentication", "Authorized", "Captured", "Failed"],
    riskBehavior: "Show merchant, amount, card, and liability language in the same confirmation surface.",
    previewKind: "card",
  },
  {
    name: "Bank transfer",
    trigger: "User starts ACH, wire, IMPS, NEFT, or local bank transfer.",
    requiredData: ["Beneficiary", "Bank details", "Rail", "Amount", "Purpose"],
    primaryStates: ["Details", "Verification", "Review", "Submitted", "Settled"],
    riskBehavior: "Verify beneficiary details and show cut-off time, fees, and recall policy.",
    previewKind: "bank",
  },
  {
    name: "Transaction details",
    trigger: "User opens any ledger item from a list, chart, alert, or statement.",
    requiredData: ["Counterparty", "Amount", "Status", "Timeline", "Reference ID"],
    primaryStates: ["Posted", "Pending", "Failed", "Reversed", "Disputed"],
    riskBehavior: "Status explanation and support path must be visible without hiding key ledger facts.",
    previewKind: "details",
  },
  {
    name: "Dispute flow",
    trigger: "User reports an unknown, incorrect, duplicate, or failed transaction.",
    requiredData: ["Transaction", "Reason", "Evidence", "Contact", "Acknowledgement"],
    primaryStates: ["Reason", "Evidence", "Review", "Submitted", "Tracking"],
    riskBehavior: "Disclose provisional credit rules, evidence deadlines, and false claim consequences.",
    previewKind: "dispute",
  },
  {
    name: "Payment confirmation",
    trigger: "User reaches the final step before money movement.",
    requiredData: ["Recipient", "Amount", "Source", "Fees", "Arrival", "Risk copy"],
    primaryStates: ["Review", "Step-up", "Processing", "Success", "Recovery"],
    riskBehavior: "Critical irreversible payments require explicit acknowledgement before action unlocks.",
    previewKind: "confirmation",
  },
  {
    name: "Spending insights",
    trigger: "System detects a meaningful trend, anomaly, or comparison.",
    requiredData: ["Category", "Period", "Change", "Confidence", "Action"],
    primaryStates: ["Insight", "Explain", "Dismiss", "Act", "Learned"],
    riskBehavior: "Use confidence framing when insight could affect a financial decision.",
    previewKind: "insight",
  },
  {
    name: "Budget tracking",
    trigger: "User creates, monitors, or adjusts spend limits.",
    requiredData: ["Budget", "Category", "Period", "Current spend", "Forecast"],
    primaryStates: ["On track", "Approaching", "Exceeded", "Adjusted"],
    riskBehavior: "Warn before limits are exceeded and make resets explicit.",
    previewKind: "budget",
  },
  {
    name: "Risk alert",
    trigger: "System flags suspicious device, transaction, exposure, or account behavior.",
    requiredData: ["Risk source", "Severity", "Affected account", "Recommended action"],
    primaryStates: ["New", "Acknowledged", "Investigating", "Resolved"],
    riskBehavior: "Use persistent, non-dismissable UI for high-risk account protection actions.",
    previewKind: "risk",
  },
  {
    name: "KYC onboarding",
    trigger: "User must verify identity before product access or increased limits.",
    requiredData: ["Identity", "Address", "Document", "Selfie", "Business details"],
    primaryStates: ["Not started", "In review", "Approved", "Needs action", "Rejected"],
    riskBehavior: "Explain why data is required and how review status affects access.",
    previewKind: "kyc",
  },
  {
    name: "Consent-based data sharing",
    trigger: "User connects accounts, grants open-banking access, or shares financial data.",
    requiredData: ["Provider", "Data scopes", "Duration", "Revocation path"],
    primaryStates: ["Request", "Granted", "Expiring", "Revoked"],
    riskBehavior: "Scopes must be readable, revocation must be discoverable, and consent duration must be explicit.",
    previewKind: "consent",
  },
  {
    name: "Account connection",
    trigger: "User links an external bank, card, payroll, brokerage, or wallet account.",
    requiredData: ["Provider", "Credentials", "Permissions", "Sync status"],
    primaryStates: ["Select", "Authenticate", "Syncing", "Connected", "Broken"],
    riskBehavior: "Show security handling, last sync, and broken-connection recovery.",
    previewKind: "connection",
  },
  {
    name: "Subscription management",
    trigger: "User manages a recurring plan, mandate, or billing agreement.",
    requiredData: ["Merchant", "Amount", "Cadence", "Next charge", "Cancellation policy"],
    primaryStates: ["Active", "Paused", "Past due", "Cancelled"],
    riskBehavior: "Make recurring charge timing, cancellation effect, and mandate status explicit.",
    previewKind: "subscription",
  },
]

export const fintechIconRules = [
  "Navigation icons identify destinations, not decoration.",
  "Action icons must be paired with labels unless the action is globally familiar.",
  "Status icons always pair with text and tone.",
  "Security icons are reserved for verified, encrypted, locked, and risky states.",
  "Empty-state icons stay quiet and explain what data is missing.",
]

export const fintechLayoutRules = [
  "Dashboards use 12 columns on desktop, 6 on tablet, and single-column priority stacking on mobile.",
  "Analytics pages keep filters pinned above charts and reserve the right rail for explainers or saved views.",
  "Transaction lists use dense rows with persistent amount, counterparty, date, status, and action affordances.",
  "Detail pages use a summary header, ledger facts, timeline, documents, then support actions.",
  "Settings pages separate profile, security, limits, notifications, and billing into predictable groups.",
  "Onboarding screens use one primary decision per step with visible progress and save/resume behavior.",
  "Mobile layouts prioritize balance, primary action, pending risk, and recent activity above the fold.",
]
